### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by Rajakob** [haklein/Powder-O-Matic#2]
Guten Tag. Ich habe damit begonnen Ihr Projekt umzusetzen. Besten Dank vorweg eine wirklich tolle Lösung.  Ich verwende eine AnD FX120i jedoch scheitert die automatische Tarierung. Könne Sie mir bitte die Einstellungen mitteilen, welche Sie an der Waage gemacht haben damit die Waage von extern Tariert werden kann? Ebenfalls kann Ich nicht wie in Ihrem letzten Video die einzelnen Einstellungen z.B Trickler mA einstellen. Ist der Code noch Ihre „alte“ Version? Besten Dank für Ihre Hife. Freundliche Grüsse aus der Schweiz. Raoul Jakob
J.raoul@hotmail.com

**Comment by haklein** [comment]
Die Einstellungen sollten jetzt wieder funktionieren. Die Einstellungen an der Waage kann ich derzeit nicht nachsehen, aber die optionen sind so weit schluessig im Handbuch erklaert.
