### ISSUE TITLE
Display set-up menu

### ISSUE THREAD

**Issue by RowanNL** [haklein/Powder-O-Matic#3]
Hello,

I've got the program and trickler working but i have a problem with entering the set-up menu.
When pressing the rotary encoder while start up it will enter set up but the whole screen just turns white.
I just used your program, I've tried both displays but the both do the same. 

Can you help me out?

Thx!

I really love the powder-o-matic! It would be really nice to have the set up working as well.

**Comment by RowanNL** [comment]
Gütentag, Wenn ich durch Drücken beim Start in das Setup-Menü gehen möchte, bleibt der Bildschirm weiß. Kannst du mir helfen? Es funktioniert auf deinem YouTube-Kanal...

danke im Voraus

**Comment by RowanNL** [comment]
Hello Harald,

Could you help us?

regards,

**Comment by RowanNL** [comment]
Hello Harald,

can you help us?

regards,

**Comment by haklein** [comment]
I've found the reason for this issue with new arduino versions. Will be fixed in a few minutes.
